name: install-py
description: 'Build, test, and install a pybind11 package, caching the installers.'
inputs:
  package:
    required: true
  hash:
    required: true
  cpack:
    default: false
runs:
  using: "composite"
  steps:
    - name: cache
      uses: actions/cache@v4
      id: cache_wheel
      with:
        path: packages/${{inputs.package}}
        key: packages-${{inputs.package}}-${{ runner.os }}-${{ runner.arch }}-${{ inputs.hash }}
    - if: steps.cache_navground_core.outputs.cache-hit != 'true'
      name: build and test
      shell: bash
      run: |
        mkdir -p ${{inputs.package}}/build
        cd ${{inputs.package}}/build
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON ..
        cmake --build . -j 4
        mv dist ${{github.workspace}}/packages/${{inputs.package}}
    - name: cpack
      if: ${{steps.cache_navground_core.outputs.cache-hit != 'true' && inputs.cpack == 'true'}}
      working-directory: ${{inputs.package}}/build
      shell: bash
      run: |
        cpack
        mv packages/* ${{github.workspace}}/packages/${{inputs.package}}
    - name: install
      shell: bash
      run: |
        find packages/${{inputs.package}} -name '*.whl' -exec pip install {}[all] \;
        find packages/${{inputs.package}} -name '*.deb' -exec sudo apt-get install {} \;
    - name: test
      if: ${{steps.cache_navground_core.outputs.cache-hit != 'true'}}
      working-directory: ${{inputs.package}}/build
      shell: bash
      run: ctest
    - name: Upload test logs
      uses: actions/upload-artifact@v4
      if: failure() && steps.test.outcome == 'failure'
      with:
        name: ${{inputs.package}}-LastTest.log
        path: ${{inputs.package}}/build/Testing/Temporary/LastTest.log
        if-no-files-found: ignore
        retention-days: 5
