option(CPACK_INCLUDE_DEPS "Whether to include the dependencies" OFF)
option(CPACK_INSTALL_NAVGROUND_IN_OPT "Whether to install navground in /opt"
       OFF)

set(CPACK_PACKAGE_NAME ${CMAKE_PROJECT_NAME})
set(CPACK_PACKAGE_DESCRIPTION "The navground core library")
set(CPACK_PACKAGE_VENDOR "IDSIA")
set(CPACK_VERBATIM_VARIABLES YES)
set(CPACK_PACKAGE_INSTALL_DIRECTORY navground)
set(CPACK_OUTPUT_FILE_PREFIX "packages")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/idsia-robotics/navground")

if((NOT WIN32) AND CPACK_INSTALL_NAVGROUND_IN_OPT)
  set(CPACK_PACKAGING_INSTALL_PREFIX "/opt/navground")
endif()

if(WIN32)
  set(CPACK_GENERATOR NSIS)
elseif(APPLE)
  set(CPACK_PRODUCTBUILD_IDENTIFIER "org.idsia.navground.core")
  set(CPACK_PRODUCTBUILD_DOMAINS true)
  set(CPACK_PRODUCTBUILD_DOMAINS_ANYWHERE true)
  set(CPACK_PRODUCTBUILD_DOMAINS_USER true)
  set(CPACK_PRODUCTBUILD_DOMAINS_ROOT true)
elseif(UNIX)
  set(CPACK_GENERATOR DEB)
  set(CPACK_RPM_PACKAGE_LICENSE "MIT")
endif()

set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(CPACK_PACKAGE_CONTACT "jerome@idsia.ch")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Jérôme Guzzi")
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_COMPONENTS_GROUPING ALL_COMPONENTS_IN_ONE) # ONE_PER_GROUP)
set(CPACK_DEB_COMPONENT_INSTALL OFF)
set(CPACK_STRIP_FILES ON)
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)

if(CPACK_INCLUDE_DEPS)
  set(CPACK_DEBIAN_PACKAGE_DEPENDS
      "libargparse-dev, libeigen3-dev, libyaml-cpp-dev")
else()
  # set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6, libgcc-s1, libstdc++6, zlib1g")
endif()

set(CPACK_PACKAGE_FILE_NAME
    ${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}
)

include(CPack)
