services:
  source-deps:
    image: jeguzzi/navground:source-deps
    build:
      dockerfile: Dockerfile.source-deps
      context: .
  binary-deps:
    image: jeguzzi/navground
    build:
      dockerfile: Dockerfile
      context: .
  python:
    image: jeguzzi/navground:python
    build:
      dockerfile: Dockerfile.python
      context: .
    ports:
      - "8888:8888"
