FROM python:3.12-slim as deps
MAINTAINER Jerome Guzzi "jerome@idsia.ch"

ENV DEBIAN_FRONTEND="noninteractive" TZ="Europe/Zurich"

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y \
    libgeos++-dev libhdf5-dev libeigen3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install numpy h5py

FROM deps as build

RUN apt-get update && apt-get install -y \
    cmake git libclang-16-dev clang-16 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install clang==16.0.6 colcon-common-extensions git+https://github.com/jeguzzi/pybind11_mkdoc@rst

RUN mkdir /ws && cd /ws \
    && export COLCON_DEFAULTS_FILE=/ws/src/navground/colcon/defaults.yaml \
    && export CC=/usr/bin/clang-16 \
    && export CXX=/usr/bin/clang++-16 \
    && git clone https://github.com/BlueBrain/HighFive.git src/HighFive \
    && git clone https://github.com/p-ranav/argparse.git src/argparse \
    && git clone https://github.com/idsia-robotics/navground.git src/navground \
    && git clone https://github.com/ament/ament_cmake.git src/ament_cmake \
    && git clone https://github.com/ament/ament_package.git src/ament_package\
    && git clone https://github.com/jbeder/yaml-cpp.git src/yaml-cpp \
    && git clone https://github.com/pybind/pybind11.git src/pybind11 \
    # && git clone https://gitlab.com/libeigen/eigen src/libeigen3-dev \
    && colcon build --metas src/navground/colcon/navground.meta --packages-up-to \
        navground_sim navground_demos navground_examples navground_examples_py

FROM deps as install

WORKDIR /ws

COPY --from=build /ws/install /ws/install
COPY ./entrypoint.slim.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]