FROM jeguzzi/navground:latest

RUN apt-get update && apt-get install -y \
    software-properties-common \
    && add-apt-repository universe \
    && curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    ros-rolling-ament-cmake \
    ros-rolling-ament-package \
    && rm -rf /var/lib/apt/lists/*

RUN source /navground_venv/bin/activate \
    && pip install colcon-common-extensions

RUN mkdir -p /ws/src \
    && source /navground_venv/bin/activate \
    && cd /ws \
    && colcon build --merge-install 

COPY ./entrypoint_dev.sh /entrypoint.sh
