FROM jeguzzi/navground:latest

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    && rm -rf /var/lib/apt/lists/*

RUN source "/navground_venv/bin/activate" \
    && pip install colcon-common-extensions

RUN mkdir -p /ws/src \
    && cd /ws \
    && colcon --merge-install build

COPY ./entrypoint_dev.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]
