---
services:
  source-deps:
    image: jeguzzi/navground:source-deps
    build:
      dockerfile: Dockerfile.source-deps
      context: .
  binary-deps:
    image: jeguzzi/navground:binary-deps
    build:
      dockerfile: Dockerfile.binary-deps
      context: .
  ros:
    image: jeguzzi/navground:ros
    build:
      dockerfile: Dockerfile.ros
      context: .
  python:
    image: jeguzzi/navground:python
    build:
      dockerfile: Dockerfile.python
      context: .
  dev:
    image: jeguzzi/navground:dev
    build:
      dockerfile: Dockerfile.dev
      context: .
  notebook:
    image: jeguzzi/navground:notebook
    build:
      dockerfile: Dockerfile.notebook
      context: .
    ports:
      - "8888:8888"
