FROM python:3.12-slim as download

RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 https://github.com/idsia-robotics/navground.git

FROM python:3.12-slim

RUN pip install navground[all] notebook

COPY --from=download /navground/docs/tutorials /tutorials

CMD ["/bin/bash", "-c", "cd /tutorials && jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root -y"]