version: '3'
services:
  source:
    image: jeguzzi/navground:ubuntu22.04
    build:
      dockerfile: Dockerfile
      context: .
  binary:
    image: binary
    build:
      dockerfile: Dockerfile.binary
      context: .
  all-at-once:
    image: jeguzzi/navground:ubuntu24.04
    build:
      dockerfile: Dockerfile.all
      context: .
  slim:
    image: jeguzzi/navground:slim
    build:
      dockerfile: Dockerfile.slim
      context: .