name: install-cpp
description: 'Build, test, and install a cpp package, caching the installer.'
inputs:
  package:
    required: true
  hash:
    required: true
runs:
  using: "composite"
  steps:
    - name: cache
      uses: actions/cache@v4
      id: cache_package
      with:
        path: packages/${{inputs.package}}
        key: packages-${{inputs.package}}-${{ runner.os }}-${{ runner.arch }}-${{ inputs.hash }}
    - if: steps.cache_package.outputs.cache-hit != 'true'
      name: build and test
      id: test
      shell: bash
      run: |
        mkdir -p ${{inputs.package}}/build
        cd ${{inputs.package}}/build
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON ..
        cmake --build . -j 4
        ctest
        cpack
        mv packages ${{github.workspace}}/packages/${{inputs.package}}
    - name: Upload test logs
      uses: actions/upload-artifact@v4
      if: failure() && steps.test.outcome == 'failure'
      working-directory: ${{inputs.package}}/build
      with:
        name: ${{inputs.package}}-LastTest.log
        path: Testing/Temporary/LastTest.log
        if-no-files-found: ignore
        retention-days: 5
    - name: install
      shell: bash
      run: |
        sudo apt-get install ./packages/${{inputs.package}}/*.deb