#goal definition
geometry_msgs/PointStamped target_point
geometry_msgs/PoseStamped target_pose
float32 position_tolerance 0.1
float32 orientation_tolerance 0.05
---
#result definition
---
#feedback
float32 distance
float32 remaining_time
