@echo off
set "NAVGROUND_ROOT=%~dp0"
set "NAVGROUND_DLL_PATH=%NAVGROUND_ROOT%\bin"
set "CMAKE_PREFIX_PATH=%NAVGROUND_ROOT%;%CMAKE_PREFIX_PATH%"
set "Path=%NAVGROUND_ROOT%bin;%NAVGROUND_ROOT%lib;%Path%"
set "NAVGROUND_PLUGINS_PREFIX=%NAVGROUND_ROOT%;%NAVGROUND_PLUGINS_PREFIX%"