name: build_wheel

on:
  workflow_run:
    workflows: [build_py]
    types: [completed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show environment
        run: echo "🔎 The name of your branch is ${{ github.ref }}."
