name: git describe
on:
  workflow_dispatch:
jobs:
  describe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: true
      - run: git tag
      - run: git describe --tags --dirty
