name: git describe
on:
  workflow_dispatch:
jobs:
  describe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install setuptools-git-versioning
      - run: setuptools-git-versioning
      - run: git tag
      - run: git describe --tags --dirty
