name: Test
on: workflow_dispatch
env:
  COLCON_DEFAULTS_FILE: src/navground/colcon/defaults.yaml
jobs:
  build_deps:
    name: build deps
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: src/navground
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install colcon-common-extensions vcstool 
      - run: vcs import --shallow --input src/navground/colcon/external.repos
      - run: colcon build --metas src/navground/colcon/navground.meta --packages-up-to Eigen3 GEOS HDF5 HighFive YAML_CPP ament_cmake argparse pybind11
      - name: archive install
        uses: actions/upload-artifact@v4
        with:
          name: install_deps_${{runner.os}}
          path: install
      - name: archive build
        uses: actions/upload-artifact@v4
        with:
          name: build_deps_${{runner.os}}
          path: build
  build_cpp:
    if: false
    needs: build_deps
    name: build navground cpp packages
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: src/navground
      - uses: actions/download-artifact@v4
        with:
          name: install_deps_${{runner.os}}
          path: install
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install colcon-common-extensions
      - run: colcon build --metas src/navground/colcon/navground.meta --packages-select navground_core
      - name: archive install
        uses: actions/upload-artifact@v4
        with:
          name: install_cpp
          path: install
  build_py:
    if: false
    needs: build_cpp
    runs-on: macos-latest
    name: build navground python packages
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
        with:
          path: src/navground
      - uses: actions/download-artifact@v4
        with:
          name: install_cpp_${{runner.os}}
          path: install
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install colcon-common-extensions
      - run: colcon build --metas src/navground/colcon/navground.meta --packages-select navground_py
      - name: archive install
        uses: actions/upload-artifact@v4
        with:
          name: install_${{runner.os}}_py${{matrix.python-version}}
          path: install
       

        
